const PrivacyPolicy = () => {
  return (
    <section className="min-h-screen bg-white py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-heading font-bold text-foreground mb-2">Privacy Policy</h1>
        <p className="text-lg font-semibold text-primary mb-6">BH Tree Service</p>

        <div className="space-y-6 text-foreground/80 text-sm leading-relaxed">
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You respond to our advertisements and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to contact and support you, as well as to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <div>
            <h2 className="text-xl font-bold text-foreground mb-2">Interpretation and Definitions</h2>
            <h3 className="text-lg font-bold text-foreground mb-1">Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          </div>

          <div>
            <h3 className="text-lg font-bold text-foreground mb-1">Definitions</h3>
            <p className="mb-2">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BH Tree Service.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the advertisement, website, or application.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-foreground mb-2">Collecting and Using Your Personal Data</h2>
            <h3 className="text-lg font-bold text-foreground mb-1">Types of Data Collected</h3>
            <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>First and last name</li>
              <li>Email address</li>
              <li>Phone number</li>
              <li>Location details such as your address, city or country</li>
              <li>Any other data such as personal preferences, requirements or comments</li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-bold text-foreground mb-1">Use of Your Personal Data</h3>
            <p className="mb-2">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
              <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
              <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
              <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li><strong>For other purposes:</strong> We may use Your information for data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
            </ul>
          </div>

          <div>
            <p className="mb-2">We may share Your personal information in the following situations:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
              <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
              <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-bold text-foreground mb-1">Retention of Your Personal Data</h3>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          </div>

          <div>
            <h3 className="text-lg font-bold text-foreground mb-1">Transfer of Your Personal Data</h3>
            <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-foreground mb-2">Disclosure of Your Personal Data</h2>
            <h3 className="text-lg font-bold text-foreground mb-1">Law Enforcement</h3>
            <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
          </div>

          <div>
            <h3 className="text-lg font-bold text-foreground mb-1">Other Legal Requirements</h3>
            <p className="mb-2">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-bold text-foreground mb-2">Security of Your Personal Data</h2>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-foreground mb-2">Links to Other Websites</h2>
            <p>Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-foreground mb-2">Changes to this Privacy Policy</h2>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>
            <p className="mt-2 text-foreground/60">This Privacy Policy was last updated on 2024/04/03.</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-foreground mb-2">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us via email at <a href="mailto:info@bhtreeservice.com" className="text-primary font-semibold underline">info@bhtreeservice.com</a></p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default PrivacyPolicy;
